– name: install python package
  become: true
  apt: 
    name: python
    state: latest
    update_cache: yes
    
- name: update apt packages
  apt: 
    update_cache: yes
  
- name: upgrade apt packages
  apt: 
    upgrade: yes
  
– name: install nodejs package
  become: yes
  apt: 
    name: nodejs 
    state: latest
    update_cache: yes
  
– name: install npm package
  become: yes
  apt: 
    name: npm 
    state: latest
    update_cache: yes
  
– name: install pm2 package
  become: yes
  npm: 
    name: pm2 
    state: latest 
    update_cache: yes
