– name: "install python package"
  become: true
  apt: 
    name: python
    state: latest 
    update_cache: yes
  
- name: "update apt packages"
  become: true
  apt: 
    update_cache: yes
  
- name: "upgrade apt packages"
  become: true
  apt: 
    upgrade: yes
  
– name: "install nodejs package"
  become: true
  apt: 
    name: nodejs 
    state: latest 
    update_cache: yes
  
– name: "install npm package"
  become: true
  apt: 
    name: npm 
    state: latest
    update_cache: yes
  
– name: "install pm2 package"
  become: true
  npm: 
    name: pm2 
    state: latest 
    update_cache: yes
