– name: "install python package"
  apt: name=python state=latest update_cache=yes
  
- name: "update apt packages"
  apt: update_cache=yes
  
- name: "upgrade apt packages"
  apt: upgrade=yes
  
– name: "install nodejs package"
  apt: name=nodejs state=latest update_cache=yes
  
– name: "install npm package"
  apt: name=npm state=latest update_cache=yes
  
– name: "install pm2 package"
  npm: name=pm2 state=latest update_cache=yes
